[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"
  NOKOGIRI_USE_SYSTEM_LIBRARIES = "true"
  BUNDLE_WITHOUT = "development"

[[plugins]]
package = "netlify-plugin-ruby"
